* Overview

/Entmut: for when your data structures are feeling treeish./

This package provides several implementations of a [[http://en.wikipedia.org/wiki/Tree_(data_structure)][tree data structure]] and
iterator-like traits for working with them.

This is a work in progress. Several abstractions are still being
planned/explored/experimented with.

** Traits

| Trait             | Description                     | Tree data                        | Tree structure |
|-------------------+---------------------------------+----------------------------------+----------------|
| =entmut::Nav=     | Fixed-topology tree navigation. | Read-only or internally mutable. | Read-only.     |

** Implementations

 - =entmut::fixed::Tree= :: fixed-layout tree structures with good memory
      locality guarantees
 - =entmut::owned::Tree= :: single-ownership structures wherein a parent owns
      its children
 - =entmut::shared::Tree= :: reference-counted pointers that can be shared
      between trees

* Copyright

Copyright 2015, Donald S. Black.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License.  You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied.  See the License for the
specific language governing permissions and limitations under the License.

